PythonVersion="3.7.9"
virtualEnvName="antenv"
compressedVirtualEnvFile="antenv.tar.gz"
OperationId="|0Ev72OASm78=.6d163708_"
SourceDirectoryInBuildContainer="/tmp/8d895db8eac4618"
PlatformName="python"
